name: build
on: 
  schedule:
    - cron: "* * * * *"
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Generate
      run: |
        ls -a
        go version
        chmod +x generate.sh
        ./generate.sh
        ls -al ./publish/
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with: 
        files: ./publish/geoip.dat
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
