name: build
on: 
  schedule:
    - cron: "*/3 * * * *"
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Set GOPATH
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash

    - name: Generate
      run: |
        chmod +x generate.sh
        ./generate.sh

    - name: Create Latest tag
      uses: EndBug/latest-tag@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifact: geoip.dat
        tag: "latest"
        token: ${{ secrets.GITHUB_TOKEN }}
